server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shop?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: 142567896
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:com/etc/mapper/xml/*.xml
  type-aliases-package: com.etc.entity

logging:
  level:
    org.apache: info
    com.etc.mapper: debug
  file:
    name: ./logs/web.log
  pattern:
    console: "%d [%t] %-5p [%c] - %m%n"

