package com.etc.entity;

public class Advice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice.advid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Integer advid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice.type
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice.advtext
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private String advtext;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice.advid
     *
     * @return the value of advice.advid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Integer getAdvid() {
        return advid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice.advid
     *
     * @param advid the value for advice.advid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setAdvid(Integer advid) {
        this.advid = advid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice.type
     *
     * @return the value of advice.type
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice.type
     *
     * @param type the value for advice.type
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice.advtext
     *
     * @return the value of advice.advtext
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public String getAdvtext() {
        return advtext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice.advtext
     *
     * @param advtext the value for advice.advtext
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setAdvtext(String advtext) {
        this.advtext = advtext;
    }
}