package com.etc.entity;

public class Analysis {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis.aid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis.uid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis.type
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analysis.result
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private String result;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis.aid
     *
     * @return the value of analysis.aid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis.aid
     *
     * @param aid the value for analysis.aid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis.uid
     *
     * @return the value of analysis.uid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis.uid
     *
     * @param uid the value for analysis.uid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis.type
     *
     * @return the value of analysis.type
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis.type
     *
     * @param type the value for analysis.type
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analysis.result
     *
     * @return the value of analysis.result
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analysis.result
     *
     * @param result the value for analysis.result
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setResult(String result) {
        this.result = result;
    }
}