package com.etc.entity;

import java.util.Date;

public class Bloodsugar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bloodsugar.bid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Integer bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bloodsugar.uid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bloodsugar.bloodsugar
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Integer bloodsugar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bloodsugar.date
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bloodsugar.bid
     *
     * @return the value of bloodsugar.bid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bloodsugar.bid
     *
     * @param bid the value for bloodsugar.bid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bloodsugar.uid
     *
     * @return the value of bloodsugar.uid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bloodsugar.uid
     *
     * @param uid the value for bloodsugar.uid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bloodsugar.bloodsugar
     *
     * @return the value of bloodsugar.bloodsugar
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Integer getBloodsugar() {
        return bloodsugar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bloodsugar.bloodsugar
     *
     * @param bloodsugar the value for bloodsugar.bloodsugar
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setBloodsugar(Integer bloodsugar) {
        this.bloodsugar = bloodsugar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bloodsugar.date
     *
     * @return the value of bloodsugar.date
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bloodsugar.date
     *
     * @param date the value for bloodsugar.date
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setDate(Date date) {
        this.date = date;
    }
}