package com.etc.entity;

import java.util.Date;

public class Bloodpress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bloodpress.bpid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Integer bpid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bloodpress.uid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bloodpress.systolic
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Integer systolic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bloodpress.diastolic
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Integer diastolic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bloodpress.date
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bloodpress.bpid
     *
     * @return the value of bloodpress.bpid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Integer getBpid() {
        return bpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bloodpress.bpid
     *
     * @param bpid the value for bloodpress.bpid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setBpid(Integer bpid) {
        this.bpid = bpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bloodpress.uid
     *
     * @return the value of bloodpress.uid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bloodpress.uid
     *
     * @param uid the value for bloodpress.uid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bloodpress.systolic
     *
     * @return the value of bloodpress.systolic
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Integer getSystolic() {
        return systolic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bloodpress.systolic
     *
     * @param systolic the value for bloodpress.systolic
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setSystolic(Integer systolic) {
        this.systolic = systolic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bloodpress.diastolic
     *
     * @return the value of bloodpress.diastolic
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Integer getDiastolic() {
        return diastolic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bloodpress.diastolic
     *
     * @param diastolic the value for bloodpress.diastolic
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setDiastolic(Integer diastolic) {
        this.diastolic = diastolic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bloodpress.date
     *
     * @return the value of bloodpress.date
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bloodpress.date
     *
     * @param date the value for bloodpress.date
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setDate(Date date) {
        this.date = date;
    }
}