package com.etc.entity;

import java.util.Date;

public class Bodydata {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bodydata.bid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Integer bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bodydata.uid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bodydata.height
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Double height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bodydata.weight
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Double weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bodydata.date
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bodydata.bid
     *
     * @return the value of bodydata.bid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bodydata.bid
     *
     * @param bid the value for bodydata.bid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bodydata.uid
     *
     * @return the value of bodydata.uid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bodydata.uid
     *
     * @param uid the value for bodydata.uid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bodydata.height
     *
     * @return the value of bodydata.height
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Double getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bodydata.height
     *
     * @param height the value for bodydata.height
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setHeight(Double height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bodydata.weight
     *
     * @return the value of bodydata.weight
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bodydata.weight
     *
     * @param weight the value for bodydata.weight
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bodydata.date
     *
     * @return the value of bodydata.date
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bodydata.date
     *
     * @param date the value for bodydata.date
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setDate(Date date) {
        this.date = date;
    }
}