package com.etc.entity;

public class Fitness {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fitness.fid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Integer fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fitness.title
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fitness.text
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fitness.pic
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fitness.videopath
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private String videopath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fitness.fid
     *
     * @return the value of fitness.fid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fitness.fid
     *
     * @param fid the value for fitness.fid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fitness.title
     *
     * @return the value of fitness.title
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fitness.title
     *
     * @param title the value for fitness.title
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fitness.text
     *
     * @return the value of fitness.text
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fitness.text
     *
     * @param text the value for fitness.text
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fitness.pic
     *
     * @return the value of fitness.pic
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fitness.pic
     *
     * @param pic the value for fitness.pic
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fitness.videopath
     *
     * @return the value of fitness.videopath
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public String getVideopath() {
        return videopath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fitness.videopath
     *
     * @param videopath the value for fitness.videopath
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setVideopath(String videopath) {
        this.videopath = videopath;
    }
}