package com.etc.entity;

import java.util.Date;

public class Hertrate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hertrate.hid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Integer hid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hertrate.uid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hertrate.hertrate
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Integer hertrate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hertrate.date
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hertrate.hid
     *
     * @return the value of hertrate.hid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hertrate.hid
     *
     * @param hid the value for hertrate.hid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hertrate.uid
     *
     * @return the value of hertrate.uid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hertrate.uid
     *
     * @param uid the value for hertrate.uid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hertrate.hertrate
     *
     * @return the value of hertrate.hertrate
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Integer getHertrate() {
        return hertrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hertrate.hertrate
     *
     * @param hertrate the value for hertrate.hertrate
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setHertrate(Integer hertrate) {
        this.hertrate = hertrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hertrate.date
     *
     * @return the value of hertrate.date
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hertrate.date
     *
     * @param date the value for hertrate.date
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setDate(Date date) {
        this.date = date;
    }
}