package com.etc.entity;

public class Myadvice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myadvice.myadvid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Integer myadvid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myadvice.advid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Integer advid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myadvice.uid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myadvice.myadvid
     *
     * @return the value of myadvice.myadvid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Integer getMyadvid() {
        return myadvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myadvice.myadvid
     *
     * @param myadvid the value for myadvice.myadvid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setMyadvid(Integer myadvid) {
        this.myadvid = myadvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myadvice.advid
     *
     * @return the value of myadvice.advid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Integer getAdvid() {
        return advid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myadvice.advid
     *
     * @param advid the value for myadvice.advid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setAdvid(Integer advid) {
        this.advid = advid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myadvice.uid
     *
     * @return the value of myadvice.uid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myadvice.uid
     *
     * @param uid the value for myadvice.uid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}