package com.etc.entity;

import java.util.ArrayList;
import java.util.List;

public class MyadviceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table myadvice
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table myadvice
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table myadvice
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myadvice
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public MyadviceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myadvice
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myadvice
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myadvice
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myadvice
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myadvice
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myadvice
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myadvice
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myadvice
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myadvice
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myadvice
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table myadvice
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMyadvidIsNull() {
            addCriterion("myadvid is null");
            return (Criteria) this;
        }

        public Criteria andMyadvidIsNotNull() {
            addCriterion("myadvid is not null");
            return (Criteria) this;
        }

        public Criteria andMyadvidEqualTo(Integer value) {
            addCriterion("myadvid =", value, "myadvid");
            return (Criteria) this;
        }

        public Criteria andMyadvidNotEqualTo(Integer value) {
            addCriterion("myadvid <>", value, "myadvid");
            return (Criteria) this;
        }

        public Criteria andMyadvidGreaterThan(Integer value) {
            addCriterion("myadvid >", value, "myadvid");
            return (Criteria) this;
        }

        public Criteria andMyadvidGreaterThanOrEqualTo(Integer value) {
            addCriterion("myadvid >=", value, "myadvid");
            return (Criteria) this;
        }

        public Criteria andMyadvidLessThan(Integer value) {
            addCriterion("myadvid <", value, "myadvid");
            return (Criteria) this;
        }

        public Criteria andMyadvidLessThanOrEqualTo(Integer value) {
            addCriterion("myadvid <=", value, "myadvid");
            return (Criteria) this;
        }

        public Criteria andMyadvidIn(List<Integer> values) {
            addCriterion("myadvid in", values, "myadvid");
            return (Criteria) this;
        }

        public Criteria andMyadvidNotIn(List<Integer> values) {
            addCriterion("myadvid not in", values, "myadvid");
            return (Criteria) this;
        }

        public Criteria andMyadvidBetween(Integer value1, Integer value2) {
            addCriterion("myadvid between", value1, value2, "myadvid");
            return (Criteria) this;
        }

        public Criteria andMyadvidNotBetween(Integer value1, Integer value2) {
            addCriterion("myadvid not between", value1, value2, "myadvid");
            return (Criteria) this;
        }

        public Criteria andAdvidIsNull() {
            addCriterion("advid is null");
            return (Criteria) this;
        }

        public Criteria andAdvidIsNotNull() {
            addCriterion("advid is not null");
            return (Criteria) this;
        }

        public Criteria andAdvidEqualTo(Integer value) {
            addCriterion("advid =", value, "advid");
            return (Criteria) this;
        }

        public Criteria andAdvidNotEqualTo(Integer value) {
            addCriterion("advid <>", value, "advid");
            return (Criteria) this;
        }

        public Criteria andAdvidGreaterThan(Integer value) {
            addCriterion("advid >", value, "advid");
            return (Criteria) this;
        }

        public Criteria andAdvidGreaterThanOrEqualTo(Integer value) {
            addCriterion("advid >=", value, "advid");
            return (Criteria) this;
        }

        public Criteria andAdvidLessThan(Integer value) {
            addCriterion("advid <", value, "advid");
            return (Criteria) this;
        }

        public Criteria andAdvidLessThanOrEqualTo(Integer value) {
            addCriterion("advid <=", value, "advid");
            return (Criteria) this;
        }

        public Criteria andAdvidIn(List<Integer> values) {
            addCriterion("advid in", values, "advid");
            return (Criteria) this;
        }

        public Criteria andAdvidNotIn(List<Integer> values) {
            addCriterion("advid not in", values, "advid");
            return (Criteria) this;
        }

        public Criteria andAdvidBetween(Integer value1, Integer value2) {
            addCriterion("advid between", value1, value2, "advid");
            return (Criteria) this;
        }

        public Criteria andAdvidNotBetween(Integer value1, Integer value2) {
            addCriterion("advid not between", value1, value2, "advid");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Integer value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Integer value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Integer value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Integer value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Integer value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Integer> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Integer> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Integer value1, Integer value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Integer value1, Integer value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table myadvice
     *
     * @mbg.generated do_not_delete_during_merge Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table myadvice
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}