package com.etc.entity;

public class Myuser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.uid
     *
     * @mbg.generated Wed Nov 11 16:03:35 GMT+08:00 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.uname
     *
     * @mbg.generated Wed Nov 11 16:03:35 GMT+08:00 2020
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.upwd
     *
     * @mbg.generated Wed Nov 11 16:03:35 GMT+08:00 2020
     */
    private String upwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.uphone
     *
     * @mbg.generated Wed Nov 11 16:03:35 GMT+08:00 2020
     */
    private String uphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.umail
     *
     * @mbg.generated Wed Nov 11 16:03:35 GMT+08:00 2020
     */
    private String umail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.upic
     *
     * @mbg.generated Wed Nov 11 16:03:35 GMT+08:00 2020
     */
    private String upic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.uid
     *
     * @return the value of myuser.uid
     *
     * @mbg.generated Wed Nov 11 16:03:35 GMT+08:00 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.uid
     *
     * @param uid the value for myuser.uid
     *
     * @mbg.generated Wed Nov 11 16:03:35 GMT+08:00 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.uname
     *
     * @return the value of myuser.uname
     *
     * @mbg.generated Wed Nov 11 16:03:35 GMT+08:00 2020
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.uname
     *
     * @param uname the value for myuser.uname
     *
     * @mbg.generated Wed Nov 11 16:03:35 GMT+08:00 2020
     */
    public void setUname(String uname) {
        this.uname = uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.upwd
     *
     * @return the value of myuser.upwd
     *
     * @mbg.generated Wed Nov 11 16:03:35 GMT+08:00 2020
     */
    public String getUpwd() {
        return upwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.upwd
     *
     * @param upwd the value for myuser.upwd
     *
     * @mbg.generated Wed Nov 11 16:03:35 GMT+08:00 2020
     */
    public void setUpwd(String upwd) {
        this.upwd = upwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.uphone
     *
     * @return the value of myuser.uphone
     *
     * @mbg.generated Wed Nov 11 16:03:35 GMT+08:00 2020
     */
    public String getUphone() {
        return uphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.uphone
     *
     * @param uphone the value for myuser.uphone
     *
     * @mbg.generated Wed Nov 11 16:03:35 GMT+08:00 2020
     */
    public void setUphone(String uphone) {
        this.uphone = uphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.umail
     *
     * @return the value of myuser.umail
     *
     * @mbg.generated Wed Nov 11 16:03:35 GMT+08:00 2020
     */
    public String getUmail() {
        return umail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.umail
     *
     * @param umail the value for myuser.umail
     *
     * @mbg.generated Wed Nov 11 16:03:35 GMT+08:00 2020
     */
    public void setUmail(String umail) {
        this.umail = umail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.upic
     *
     * @return the value of myuser.upic
     *
     * @mbg.generated Wed Nov 11 16:03:35 GMT+08:00 2020
     */
    public String getUpic() {
        return upic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.upic
     *
     * @param upic the value for myuser.upic
     *
     * @mbg.generated Wed Nov 11 16:03:35 GMT+08:00 2020
     */
    public void setUpic(String upic) {
        this.upic = upic;
    }
}