package com.etc.entity;

import java.util.Date;

public class Sleep {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sleep.sid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sleep.uid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sleep.sleeptime
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Integer sleeptime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sleep.date
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sleep.sid
     *
     * @return the value of sleep.sid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sleep.sid
     *
     * @param sid the value for sleep.sid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sleep.uid
     *
     * @return the value of sleep.uid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sleep.uid
     *
     * @param uid the value for sleep.uid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sleep.sleeptime
     *
     * @return the value of sleep.sleeptime
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Integer getSleeptime() {
        return sleeptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sleep.sleeptime
     *
     * @param sleeptime the value for sleep.sleeptime
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setSleeptime(Integer sleeptime) {
        this.sleeptime = sleeptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sleep.date
     *
     * @return the value of sleep.date
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sleep.date
     *
     * @param date the value for sleep.date
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setDate(Date date) {
        this.date = date;
    }
}