package com.etc.entity;

import java.util.Date;

public class Vip {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.vid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Integer vid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.uid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.startdate
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Date startdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip.expirdate
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    private Date expirdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.vid
     *
     * @return the value of vip.vid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Integer getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.vid
     *
     * @param vid the value for vip.vid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setVid(Integer vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.uid
     *
     * @return the value of vip.uid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.uid
     *
     * @param uid the value for vip.uid
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.startdate
     *
     * @return the value of vip.startdate
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.startdate
     *
     * @param startdate the value for vip.startdate
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip.expirdate
     *
     * @return the value of vip.expirdate
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public Date getExpirdate() {
        return expirdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip.expirdate
     *
     * @param expirdate the value for vip.expirdate
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    public void setExpirdate(Date expirdate) {
        this.expirdate = expirdate;
    }
}