package com.etc.dao;

import com.etc.entity.Analysis;
import com.etc.entity.AnalysisExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AnalysisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    long countByExample(AnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int deleteByExample(AnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int insert(Analysis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int insertSelective(Analysis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    List<Analysis> selectByExample(AnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    Analysis selectByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") Analysis record, @Param("example") AnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int updateByExample(@Param("record") Analysis record, @Param("example") AnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(Analysis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analysis
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int updateByPrimaryKey(Analysis record);
}