package com.etc.dao;

import com.etc.entity.Bloodsugar;
import com.etc.entity.BloodsugarExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BloodsugarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloodsugar
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    long countByExample(BloodsugarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloodsugar
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int deleteByExample(BloodsugarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloodsugar
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer bid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloodsugar
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int insert(Bloodsugar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloodsugar
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int insertSelective(Bloodsugar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloodsugar
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    List<Bloodsugar> selectByExample(BloodsugarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloodsugar
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    Bloodsugar selectByPrimaryKey(Integer bid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloodsugar
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") Bloodsugar record, @Param("example") BloodsugarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloodsugar
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int updateByExample(@Param("record") Bloodsugar record, @Param("example") BloodsugarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloodsugar
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(Bloodsugar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloodsugar
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int updateByPrimaryKey(Bloodsugar record);
}