package com.etc.dao;

import com.etc.entity.Hertrate;
import com.etc.entity.HertrateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HertrateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hertrate
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    long countByExample(HertrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hertrate
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int deleteByExample(HertrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hertrate
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer hid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hertrate
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int insert(Hertrate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hertrate
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int insertSelective(Hertrate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hertrate
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    List<Hertrate> selectByExample(HertrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hertrate
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    Hertrate selectByPrimaryKey(Integer hid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hertrate
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") Hertrate record, @Param("example") HertrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hertrate
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int updateByExample(@Param("record") Hertrate record, @Param("example") HertrateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hertrate
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(Hertrate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hertrate
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int updateByPrimaryKey(Hertrate record);
}