package com.etc.dao;

import com.etc.entity.Myadvice;
import com.etc.entity.MyadviceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MyadviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myadvice
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    long countByExample(MyadviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myadvice
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int deleteByExample(MyadviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myadvice
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer myadvid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myadvice
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int insert(Myadvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myadvice
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int insertSelective(Myadvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myadvice
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    List<Myadvice> selectByExample(MyadviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myadvice
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    Myadvice selectByPrimaryKey(Integer myadvid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myadvice
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") Myadvice record, @Param("example") MyadviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myadvice
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int updateByExample(@Param("record") Myadvice record, @Param("example") MyadviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myadvice
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(Myadvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myadvice
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int updateByPrimaryKey(Myadvice record);
}