package com.etc.dao;

import com.etc.entity.Myuser;
import com.etc.entity.MyuserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MyuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Wed Nov 11 16:03:35 GMT+08:00 2020
     */
    long countByExample(MyuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Wed Nov 11 16:03:35 GMT+08:00 2020
     */
    int deleteByExample(MyuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Wed Nov 11 16:03:35 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Wed Nov 11 16:03:35 GMT+08:00 2020
     */
    int insert(Myuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Wed Nov 11 16:03:35 GMT+08:00 2020
     */
    int insertSelective(Myuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Wed Nov 11 16:03:35 GMT+08:00 2020
     */
    List<Myuser> selectByExample(MyuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Wed Nov 11 16:03:35 GMT+08:00 2020
     */
    Myuser selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Wed Nov 11 16:03:35 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") Myuser record, @Param("example") MyuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Wed Nov 11 16:03:35 GMT+08:00 2020
     */
    int updateByExample(@Param("record") Myuser record, @Param("example") MyuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Wed Nov 11 16:03:35 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(Myuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Wed Nov 11 16:03:35 GMT+08:00 2020
     */
    int updateByPrimaryKey(Myuser record);
}