package com.etc.dao;

import com.etc.entity.Sleep;
import com.etc.entity.SleepExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SleepMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sleep
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    long countByExample(SleepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sleep
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int deleteByExample(SleepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sleep
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sleep
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int insert(Sleep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sleep
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int insertSelective(Sleep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sleep
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    List<Sleep> selectByExample(SleepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sleep
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    Sleep selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sleep
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") Sleep record, @Param("example") SleepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sleep
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int updateByExample(@Param("record") Sleep record, @Param("example") SleepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sleep
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(Sleep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sleep
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int updateByPrimaryKey(Sleep record);
}