package com.etc.dao;

import com.etc.entity.Vip;
import com.etc.entity.VipExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    long countByExample(VipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int deleteByExample(VipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer vid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int insert(Vip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int insertSelective(Vip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    List<Vip> selectByExample(VipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    Vip selectByPrimaryKey(Integer vid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") Vip record, @Param("example") VipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int updateByExample(@Param("record") Vip record, @Param("example") VipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(Vip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip
     *
     * @mbg.generated Wed Nov 11 14:47:35 GMT+08:00 2020
     */
    int updateByPrimaryKey(Vip record);
}